version: "3.3"
services:
    mywebserver:
      image: nginx:latest
      deploy:
        replicas: 2
        mode: replicated
        endpoint_mode: dnsrr
      networks:
        - overlay
      configs:
        - source: homepage
          target: /usr/share/nginx/html
    
    myloadbalancer:
      image: haproxy:latest
      ports: 
        - "80:80"
        - "443:443"
        - "1991:1991"
      depends_on:
        - mywebserver
      networks:
        - overlay
      volumes:
        - /etc/letsencrypt/live/kartoza.letlojanedigital.co.za/haproxy:/usr/local/etc/haproxy/ssl/

      configs:
        - source: haproxyconfig
          target: /usr/local/etc/haproxy
networks:
  overlay:

configs:
  homepage:
    file: ./website/index.html
  haproxyconfig:
    file: ./haproxy/haproxy.cfg
