version: "3.3"
services:
    mywebserver:
      image: nginx:latest
      deploy:
        replicas: 2
        mode: replicated
        endpoint_mode: dnsrr
      networks:
        - overlay
    
    myloadbalancer:
      image: haproxy:latest
      ports: 
        - "80:80"
        - "443:443"
        - "1991:1991"
      depends_on:
        - mywebserver
      networks:
        - overlay
networks:
  overlay:
